version: '3.9'

services:

  node:
    build:
      context: .
      dockerfile: delivery/Dockerfile
    command: ["true"]
    restart: "no"
    environment:
      NODE_ENV: test
      SECRET: e42d8dd28adf34fc489044d5aa21e5166f22a6ef
      MONGODB_URI: mongodb://mongodb:27017/
      MONGODB_DB_MAIN: portfolio_db_test
      VITE_PROXY_HOST: http://localhost:4000
      CI: 'true'
      PORT: 4000
    networks:
      - mynet

  mongodb:
    container_name: mongodb
    image: mongo:5.0.8
    restart: always
    environment:
        MONGO_INITDB_DATABASE: portfolio_db_test
    ports:
      - 27017
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mynet

networks:
  mynet:
