worker_processes 1;

events {
    worker_connections 1024;
}

http {

    include mime.types;
    sendfile on;

    gzip on;
    gzip_http_version 1.0;
    gzip_proxied any;
    gzip_min_length 500;
    gzip_disable "MSIE [1-6]\.";
    gzip_types text/plain text/xml text/css
    text/comma-separated-values
    text/javascript
    application/x-javascript
    application/atom+xml;

    # Configuration for the server
    server {
        listen 443 default_server ssl;
        listen 80;
        listen [::]:80;
        #server_name example.org;
        ssl_certificate /var/certificates/localhost.crt;
        ssl_certificate_key /var/certificates/localhost.key;

        # Force https redirection
        # if ($scheme = http) {
        #     return 301 https://$server_name$request_uri;
        # }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            expires -1;
            add_header Pragma "no-cache";
            add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";

            try_files $uri$args $uri$args/ $uri $uri/ /index.html =404;
        }

        location /v1 {
            proxy_pass http://api:4000;
            #proxy_set_header Host $host;
        }

        location /auth {
            proxy_pass http://api:4000;
            #proxy_set_header Host $host;
        }
    }


}